version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-vite-app:prod
    container_name: my-vite-web
    ports:
      - "8080:80"    
    environment:
      API_BASE_URL: "http://31.172.72.119:8081"   
      APP_ENV: "production"
    restart: unless-stopped
